version: "3.3"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "myFirstBase"
#    volumes:
#      - /Library/pgdate:/var/lib/postgresql/data
    ports:
      - 5432:5432